# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BbrAddress',
            fields=[
                ('addrid', models.IntegerField(primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=4000)),
                ('city', models.CharField(max_length=4000)),
                ('state', models.CharField(max_length=4000)),
                ('zip', models.IntegerField()),
            ],
            options={
                'db_table': 'bbr_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrCage',
            fields=[
                ('cageid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bbr_cage',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrCoachsession',
            fields=[
                ('csid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bbr_coachsession',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrCustomer',
            fields=[
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=4000)),
                ('lname', models.CharField(max_length=4000)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=4000, null=True)),
                ('paymenttype', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'bbr_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrEmployee',
            fields=[
                ('employid', models.IntegerField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=4000)),
                ('lname', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'bbr_employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrMeetingroom',
            fields=[
                ('meetid', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bbr_meetingroom',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrMembership',
            fields=[
                ('memid', models.IntegerField(primary_key=True, serialize=False)),
                ('purchaseddate', models.DateTimeField()),
                ('type', models.CharField(max_length=4000)),
                ('enddate', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'bbr_membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrMiscequipment',
            fields=[
                ('miscid', models.IntegerField(primary_key=True, serialize=False)),
                ('bat', models.CharField(blank=True, max_length=4000, null=True)),
                ('helmet', models.CharField(blank=True, max_length=4000, null=True)),
                ('glove', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'bbr_miscequipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrPitchingmachine',
            fields=[
                ('pitchid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'bbr_pitchingmachine',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrRadar',
            fields=[
                ('radid', models.IntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                'db_table': 'bbr_radar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrRentalagreement',
            fields=[
                ('raid', models.IntegerField(primary_key=True, serialize=False)),
                ('datecreated', models.DateTimeField()),
                ('startdate', models.DateTimeField()),
                ('enddate', models.DateTimeField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('meeting_roomid', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbr_rentalagreement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrStatus',
            fields=[
                ('statusid', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=4000)),
            ],
            options={
                'db_table': 'bbr_status',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BbrUsers',
            fields=[
                ('userid', models.FloatField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('pass_field', models.CharField(db_column='pass', max_length=20)),
            ],
            options={
                'db_table': 'bbr_users',
                'managed': False,
            },
        ),
    ]
